CREATE DATABASE IF NOT EXISTS flashcards;
USE flashcards;

DROP TABLE IF EXISTS cards;

CREATE TABLE cards (
	id INT AUTO_INCREMENT PRIMARY KEY,
	question VARCHAR(255) NOT NULL,
	answer TEXT NOT NULL,
	tags VARCHAR(255) NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);